# Generated by Django 2.2 on 2021-01-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainListAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AgentID', models.CharField(max_length=30, unique=True)),
                ('CodeToMatch', models.CharField(max_length=50, unique=True)),
                ('DomainListAPP', models.CharField(blank=True, max_length=300, null=True)),
                ('DomainListInner', models.CharField(blank=True, max_length=300, null=True)),
                ('DomainListOuter', models.CharField(blank=True, max_length=300, null=True)),
                ('Active', models.IntegerField()),
                ('CreatedTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('DomainType', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DomainListAll',
            },
        ),
        migrations.CreateModel(
            name='DomainListDT3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AgentID', models.CharField(max_length=30, unique=True)),
                ('UrlIn', models.CharField(max_length=200)),
                ('UrlOut', models.CharField(max_length=200)),
                ('MyZone', models.CharField(max_length=50)),
                ('HasRun', models.IntegerField()),
                ('DomainType', models.CharField(max_length=50)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'DomainListDT3',
            },
        ),
        migrations.CreateModel(
            name='DomainTestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AgentID', models.CharField(blank=True, max_length=50, null=True)),
                ('TestTime', models.DateTimeField(blank=True, null=True)),
                ('UrlIn', models.CharField(blank=True, max_length=200, null=True)),
                ('UrlOut', models.CharField(blank=True, max_length=200, null=True)),
                ('MyIP', models.CharField(blank=True, max_length=200, null=True)),
                ('MyZone', models.CharField(blank=True, max_length=200, null=True)),
                ('CDN', models.CharField(blank=True, max_length=200, null=True)),
                ('CDNIP', models.CharField(blank=True, max_length=200, null=True)),
                ('PageLoadTime', models.FloatField(blank=True, null=True)),
                ('Browser', models.CharField(blank=True, max_length=50, null=True)),
                ('Through', models.CharField(blank=True, max_length=5, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('IPScreenshot', models.CharField(blank=True, max_length=300, null=True)),
                ('ProductScreenshot1', models.CharField(blank=True, max_length=300, null=True)),
                ('ProductScreenshot2', models.CharField(blank=True, max_length=300, null=True)),
                ('ProductScreenshot3', models.CharField(blank=True, max_length=300, null=True)),
                ('ProductScreenshot4', models.CharField(blank=True, max_length=300, null=True)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('DomainType', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DomainTestLog',
            },
        ),
        migrations.CreateModel(
            name='ForwardDomainListAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AgentID', models.CharField(max_length=30, unique=True)),
                ('UrlIn', models.CharField(max_length=200)),
                ('UrlOut', models.CharField(max_length=200)),
                ('MyZone', models.CharField(max_length=50)),
                ('DomainType', models.CharField(max_length=50)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ForwardDomainList',
            },
        ),
        migrations.CreateModel(
            name='ForwardDomainTestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AgentID', models.CharField(max_length=30)),
                ('TestTime', models.DateTimeField(blank=True, null=True)),
                ('UrlIn', models.CharField(max_length=200)),
                ('UrlOut', models.CharField(max_length=200)),
                ('MyIP', models.CharField(max_length=200)),
                ('MyZone', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=50)),
                ('Browser', models.CharField(max_length=50)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('DomainType', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ForwardDomainTestLog',
            },
        ),
        migrations.CreateModel(
            name='DomainTestLogDT3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AgentID', models.CharField(max_length=30)),
                ('TestTime', models.DateTimeField(blank=True, null=True)),
                ('UrlIn', models.CharField(max_length=200)),
                ('UrlOut', models.CharField(max_length=200)),
                ('MyIP', models.CharField(max_length=200)),
                ('MyZone', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=50)),
                ('Browser', models.CharField(max_length=50)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('DomainType', models.CharField(max_length=50)),
                ('DomainListDT3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_api.DomainListDT3')),
            ],
            options={
                'db_table': 'DomainTestLogDT3',
            },
        ),
    ]
