# Generated by Django 2.2 on 2021-01-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardDomainListAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AgentID', models.CharField(max_length=30, unique=True)),
                ('UrlIn', models.CharField(max_length=200)),
                ('UrlOut', models.CharField(max_length=200)),
                ('MyZone', models.CharField(max_length=50)),
                ('DomainType', models.CharField(max_length=50)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ForwardDomainList',
            },
        ),
        migrations.CreateModel(
            name='ForwardDomainTestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AgentID', models.CharField(max_length=30)),
                ('TestTime', models.DateTimeField(blank=True, null=True)),
                ('UrlIn', models.CharField(max_length=200)),
                ('UrlOut', models.CharField(max_length=200)),
                ('MyIP', models.CharField(max_length=200)),
                ('MyZone', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=50)),
                ('Browser', models.CharField(max_length=50)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('DomainType', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ForwardDomainTestLog',
            },
        ),
        migrations.AddField(
            model_name='domaintestlog',
            name='AgentID',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domaintestlog',
            name='Browser',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domaintestlog',
            name='Through',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domaintestlog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
